#!/usr/bin/env python3
"""Generate bookends_nerdfont_names.lua from the bundled symbols.ttf
+ the upstream Nerd Fonts glyphnames.json.

Usage:
    python3 tools/build_nerdfont_names.py \\
        --symbols-ttf /usr/lib/koreader/fonts/nerdfonts/symbols.ttf \\
        --glyphnames-json /path/to/downloaded/glyphnames.json \\
        --output bookends_nerdfont_names.lua
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fontTools not installed. Run: pip install --user fonttools")


def collect_font_codepoints(ttf_path: Path) -> set:
    """Return the set of PUA codepoints (U+E000-U+F8FF) present in the font's cmap."""
    f = TTFont(str(ttf_path))
    cmap = f.getBestCmap()
    return {cp for cp in cmap if 0xE000 <= cp <= 0xF8FF}


def parse_glyphnames(json_path: Path) -> dict:
    """Return name -> codepoint dict from upstream glyphnames.json."""
    with json_path.open() as f:
        data = json.load(f)
    out = {}
    for name, info in data.items():
        if not isinstance(info, dict):
            continue
        code = info.get("code")
        if not code:
            continue
        try:
            cp = int(code, 16)
        except ValueError:
            continue
        out[name] = cp
    return out


def emit_lua(entries, output_path: Path,
             ttf_path: Path, json_path: Path, font_cmap_size: int):
    """Write the Lua file."""
    when = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "-- Generated by tools/build_nerdfont_names.py — do not edit by hand.",
        f"-- Source font: {ttf_path}",
        f"-- Source font cmap: {font_cmap_size} glyphs in PUA range U+E000-U+F8FF",
        f"-- Source names: {json_path}",
        f"-- Generated: {when}",
        "",
        f"-- Total entries: {len(entries)}",
        "",
        "local M = {",
    ]
    for name, cp in entries:
        if '"' in name or '\\' in name:
            raise ValueError(f"unexpected character in name: {name!r}")
        lines.append(f'    {{name="{name}", code=0x{cp:04X}}},')
    lines.append("}")
    lines.append("")
    lines.append("return M")
    lines.append("")

    output_path.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--symbols-ttf", type=Path,
                    default=Path("/usr/lib/koreader/fonts/nerdfonts/symbols.ttf"))
    ap.add_argument("--glyphnames-json", type=Path, required=True)
    ap.add_argument("--output", type=Path,
                    default=Path("bookends_nerdfont_names.lua"))
    args = ap.parse_args()

    if not args.symbols_ttf.exists():
        sys.exit(f"--symbols-ttf not found: {args.symbols_ttf}")
    if not args.glyphnames_json.exists():
        sys.exit(f"--glyphnames-json not found: {args.glyphnames_json}")

    font_cps = collect_font_codepoints(args.symbols_ttf)
    print(f"Font cmap PUA glyph count: {len(font_cps)}")

    name_to_cp = parse_glyphnames(args.glyphnames_json)
    print(f"Upstream glyphnames entries: {len(name_to_cp)}")

    matched = [(name, cp) for name, cp in name_to_cp.items() if cp in font_cps]
    matched.sort(key=lambda nc: nc[0])
    print(f"Matched entries (font cmap ∩ glyphnames): {len(matched)}")

    emit_lua(matched, args.output, args.symbols_ttf, args.glyphnames_json,
             font_cmap_size=len(font_cps))
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
